services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://72.60.169.150:4005

    container_name: sitio2-frontend

    ports:
      - "4004:3000"

    restart: unless-stopped

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: sitio2-backend

    ports:
      - "4005:3001"

    env_file:
      - ./backend/.env

    restart: unless-stopped
